var fs=require("fs");
var template=require("./template");
var files="index.origin.html|test/index.origin.html|register/index.origin.html".split("|");
var htmlTemplate=fs.readFileSync(__dirname+"/template.html").toString();

for (var i = 0; i < files.length; i++) {
  var f=fs.readFileSync(__dirname+"/"+files[i]).toString();
  var lines=f.split("\n");
  var title=lines.shift().replace("\r","");
  var content=lines.join("\n");
  var s=template(htmlTemplate,{
    title,
    content
  });
  var note=`<!--
  DO NOT EDIT
  Generated by a automatic script.
  Edit ${files[i]} and run 'node build' instead.

  Copyright 2018 RDFZSU. All Rights Reserved.
  -->`;
  s=note+s;
  fs.writeFileSync(files[i].replace(".origin.html",".html"),s);
  console.log(`${files[i]} generated.`);
}
